# Generated by Django 3.2 on 2024-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDelivery',
            fields=[
                ('deliveryid', models.AutoField(db_column='DeliveryID', primary_key=True, serialize=False)),
                ('deliveryavailable', models.IntegerField(blank=True, db_column='DeliveryAvailable', null=True)),
                ('deliveryfee', models.DecimalField(blank=True, db_column='DeliveryFee', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Car_Delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='Message')),
                ('isread', models.IntegerField(blank=True, db_column='IsRead', null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('paymentdate', models.DateTimeField(db_column='PaymentDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paymentstatus', models.CharField(blank=True, db_column='PaymentStatus', max_length=9, null=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationid', models.AutoField(db_column='ReservationID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('reservationstatus', models.CharField(blank=True, db_column='ReservationStatus', max_length=9, null=True)),
            ],
            options={
                'db_table': 'Reservations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('targetid', models.IntegerField(db_column='TargetID')),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('reviewtext', models.TextField(blank=True, db_column='ReviewText', null=True)),
                ('reviewtype', models.CharField(db_column='ReviewType', max_length=7)),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('usertype', models.CharField(db_column='UserType', max_length=6)),
                ('dateregistered', models.DateTimeField(db_column='DateRegistered')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleFeatures',
            fields=[
                ('featureid', models.AutoField(db_column='FeatureID', primary_key=True, serialize=False)),
                ('featurename', models.CharField(db_column='FeatureName', max_length=50)),
                ('featurevalue', models.CharField(db_column='FeatureValue', max_length=50)),
            ],
            options={
                'db_table': 'Vehicle_Features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicleid', models.AutoField(db_column='VehicleID', primary_key=True, serialize=False)),
                ('make', models.CharField(db_column='Make', max_length=50)),
                ('model', models.CharField(db_column='Model', max_length=50)),
                ('year', models.IntegerField(db_column='Year')),
                ('dailyrate', models.DecimalField(db_column='DailyRate', decimal_places=2, max_digits=10)),
                ('location', models.CharField(db_column='Location', max_length=100)),
                ('isavailable', models.IntegerField(blank=True, db_column='IsAvailable', null=True)),
            ],
            options={
                'db_table': 'Vehicles',
                'managed': False,
            },
        ),
    ]
