# Generated by Django 3.2 on 2024-12-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbapp', '0002_auto_20241201_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='cardelivery',
            name='vehicleid',
            field=models.ForeignKey(db_column='VehicleID', default=0, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='reservationid',
            field=models.ForeignKey(db_column='ReservationID', default=0, on_delete=django.db.models.deletion.CASCADE, to='dbapp.reservations'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='renterid',
            field=models.ForeignKey(db_column='RenterID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservations',
            name='vehicleid',
            field=models.ForeignKey(db_column='VehicleID', default=0, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewerid',
            field=models.ForeignKey(db_column='ReviewerID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefeatures',
            name='vehicleid',
            field=models.ForeignKey(db_column='VehicleID', default=0, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='ownerid',
            field=models.ForeignKey(db_column='OwnerID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
