# Generated by Django 3.2 on 2024-12-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbapp', '0003_auto_20241202_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardelivery',
            name='vehicleid',
            field=models.ForeignKey(blank=True, db_column='VehicleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='reservationid',
            field=models.ForeignKey(blank=True, db_column='ReservationID', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.reservations'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='renterid',
            field=models.ForeignKey(blank=True, db_column='RenterID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='vehicleid',
            field=models.ForeignKey(blank=True, db_column='VehicleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewerid',
            field=models.ForeignKey(blank=True, db_column='ReviewerID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclefeatures',
            name='vehicleid',
            field=models.ForeignKey(blank=True, db_column='VehicleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='ownerid',
            field=models.ForeignKey(blank=True, db_column='OwnerID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
